<?php

use Illuminate\Database\Seeder;

class KabupatenTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $kabupaten = array(
            // Provinsi Aceh
            array( 'provinsi_id' => 1, 'nama' => 'Kabupaten Simeulue' ),
            array( 'provinsi_id' => 1, 'nama' => 'Kabupaten Aceh Singkil' ),
            array( 'provinsi_id' => 1, 'nama' => 'Kabupaten Aceh Selatan' ),
            array( 'provinsi_id' => 1, 'nama' => 'Kabupaten Aceh Tenggara' ),
            array( 'provinsi_id' => 1, 'nama' => 'Kabupaten Aceh Timur' ),
            array( 'provinsi_id' => 1, 'nama' => 'Kabupaten Aceh Tengah' ),
            array( 'provinsi_id' => 1, 'nama' => 'Kabupaten Aceh Barat' ),
            array( 'provinsi_id' => 1, 'nama' => 'Kabupaten Aceh Besar' ),
            array( 'provinsi_id' => 1, 'nama' => 'Kabupaten Pidie' ),
            array( 'provinsi_id' => 1, 'nama' => 'Kabupaten Bireuen' ),
            array( 'provinsi_id' => 1, 'nama' => 'Kabupaten Aceh Utara' ),
            array( 'provinsi_id' => 1, 'nama' => 'Kabupaten Aceh Barat Daya' ),
            array( 'provinsi_id' => 1, 'nama' => 'Kabupaten Gayo Lues' ),
            array( 'provinsi_id' => 1, 'nama' => 'Kabupaten Aceh Tamiang' ),
            array( 'provinsi_id' => 1, 'nama' => 'Kabupaten Nagan Raya' ),
            array( 'provinsi_id' => 1, 'nama' => 'Kabupaten Aceh Jaya' ),
            array( 'provinsi_id' => 1, 'nama' => 'Kabupaten Bener Meriah' ),
            array( 'provinsi_id' => 1, 'nama' => 'Kabupaten Pidie Jaya' ),
            array( 'provinsi_id' => 1, 'nama' => 'Kota Banda Aceh' ),
            array( 'provinsi_id' => 1, 'nama' => 'Kota Sabang' ),
            array( 'provinsi_id' => 1, 'nama' => 'Kota Langsa' ),
            array( 'provinsi_id' => 1, 'nama' => 'Kota Lhokseumawe' ),
            array( 'provinsi_id' => 1, 'nama' => 'Kota Subulussalam' ),

            // Provinsi Sumatera Utara
            array( 'provinsi_id' => 2, 'nama' => 'Kabupaten Nias' ),
            array( 'provinsi_id' => 2, 'nama' => 'Kabupaten Mandailing Natal' ),
            array( 'provinsi_id' => 2, 'nama' => 'Kabupaten Tapanuli Selatan' ),
            array( 'provinsi_id' => 2, 'nama' => 'Kabupaten Tapanuli Tengah' ),
            array( 'provinsi_id' => 2, 'nama' => 'Kabupaten Tapanuli Utara' ),
            array( 'provinsi_id' => 2, 'nama' => 'Kabupaten Toba Samosir' ),
            array( 'provinsi_id' => 2, 'nama' => 'Kabupaten Labuhan Batu' ),
            array( 'provinsi_id' => 2, 'nama' => 'Kabupaten Asahan' ),
            array( 'provinsi_id' => 2, 'nama' => 'Kabupaten Simalungun' ),
            array( 'provinsi_id' => 2, 'nama' => 'Kabupaten Dairi' ),
            array( 'provinsi_id' => 2, 'nama' => 'Kabupaten Karo' ),
            array( 'provinsi_id' => 2, 'nama' => 'Kabupaten Deli Serdang' ),
            array( 'provinsi_id' => 2, 'nama' => 'Kabupaten Langkat' ),
            array( 'provinsi_id' => 2, 'nama' => 'Kabupaten Nias Selatan' ),
            array( 'provinsi_id' => 2, 'nama' => 'Kabupaten Humbang Hasundutan' ),
            array( 'provinsi_id' => 2, 'nama' => 'Kabupaten Pakpak Bharat' ),
            array( 'provinsi_id' => 2, 'nama' => 'Kabupaten Samosir' ),
            array( 'provinsi_id' => 2, 'nama' => 'Kabupaten Serdang Bedagai' ),
            array( 'provinsi_id' => 2, 'nama' => 'Kabupaten Batu Bara' ),
            array( 'provinsi_id' => 2, 'nama' => 'Kabupaten Padang Lawas Utara' ),
            array( 'provinsi_id' => 2, 'nama' => 'Kabupaten Padang Lawas' ),
            array( 'provinsi_id' => 2, 'nama' => 'Kabupaten Labuhan Batu Selatan' ),
            array( 'provinsi_id' => 2, 'nama' => 'Kabupaten Labuhan Batu Utara' ),
            array( 'provinsi_id' => 2, 'nama' => 'Kabupaten Nias Utara' ),
            array( 'provinsi_id' => 2, 'nama' => 'Kabupaten Nias Barat' ),
            array( 'provinsi_id' => 2, 'nama' => 'Kota Sibolga' ),
            array( 'provinsi_id' => 2, 'nama' => 'Kota Tanjung Balai' ),
            array( 'provinsi_id' => 2, 'nama' => 'Kota Pematang Siantar' ),
            array( 'provinsi_id' => 2, 'nama' => 'Kota Tebing Tinggi' ),
            array( 'provinsi_id' => 2, 'nama' => 'Kota Medan' ),
            array( 'provinsi_id' => 2, 'nama' => 'Kota Binjai' ),
            array( 'provinsi_id' => 2, 'nama' => 'Kota Padangsidimpuan' ),
            array( 'provinsi_id' => 2, 'nama' => 'Kota Gunungsitoli' ),

            // Provinsi Sumatera Barat
            array( 'provinsi_id' => 3, 'nama' => 'Kabupaten Kepulauan Mentawai' ),
            array( 'provinsi_id' => 3, 'nama' => 'Kabupaten Pesisir Selatan' ),
            array( 'provinsi_id' => 3, 'nama' => 'Kabupaten Solok' ),
            array( 'provinsi_id' => 3, 'nama' => 'Kabupaten Sijunjung' ),
            array( 'provinsi_id' => 3, 'nama' => 'Kabupaten Tanah Datar' ),
            array( 'provinsi_id' => 3, 'nama' => 'Kabupaten Padang Pariaman' ),
            array( 'provinsi_id' => 3, 'nama' => 'Kabupaten Agam' ),
            array( 'provinsi_id' => 3, 'nama' => 'Kabupaten Lima Puluh Kota' ),
            array( 'provinsi_id' => 3, 'nama' => 'Kabupaten Pasaman' ),
            array( 'provinsi_id' => 3, 'nama' => 'Kabupaten Solok Selatan' ),
            array( 'provinsi_id' => 3, 'nama' => 'Kabupaten Dharmasraya' ),
            array( 'provinsi_id' => 3, 'nama' => 'Kabupaten Pasaman Barat' ),
            array( 'provinsi_id' => 3, 'nama' => 'Kota Padang' ),
            array( 'provinsi_id' => 3, 'nama' => 'Kota Solok' ),
            array( 'provinsi_id' => 3, 'nama' => 'Kota Sawah Lunto' ),
            array( 'provinsi_id' => 3, 'nama' => 'Kota Padang Panjang' ),
            array( 'provinsi_id' => 3, 'nama' => 'Kota Bukittinggi' ),
            array( 'provinsi_id' => 3, 'nama' => 'Kota Payakumbuh' ),
            array( 'provinsi_id' => 3, 'nama' => 'Kota Pariaman' ),

            // Provinsi Riau
            array( 'provinsi_id' => 4, 'nama' => 'Kabupaten Kuantan Singingi' ),
            array( 'provinsi_id' => 4, 'nama' => 'Kabupaten Indragiri Hulu' ),
            array( 'provinsi_id' => 4, 'nama' => 'Kabupaten Indragiri Hilir' ),
            array( 'provinsi_id' => 4, 'nama' => 'Kabupaten Pelalawan' ),
            array( 'provinsi_id' => 4, 'nama' => 'Kabupaten S I A K' ),
            array( 'provinsi_id' => 4, 'nama' => 'Kabupaten Kampar' ),
            array( 'provinsi_id' => 4, 'nama' => 'Kabupaten Rokan Hulu' ),
            array( 'provinsi_id' => 4, 'nama' => 'Kabupaten Bengkalis' ),
            array( 'provinsi_id' => 4, 'nama' => 'Kabupaten Rokan Hilir' ),
            array( 'provinsi_id' => 4, 'nama' => 'Kabupaten Kepulauan Meranti' ),
            array( 'provinsi_id' => 4, 'nama' => 'Kota Pekanbaru' ),
            array( 'provinsi_id' => 4, 'nama' => 'Kota D U M A I' ),

            // Provinsi Jambi
            array( 'provinsi_id' => 5, 'nama' => 'Kabupaten Kerinci' ),
            array( 'provinsi_id' => 5, 'nama' => 'Kabupaten Merangin' ),
            array( 'provinsi_id' => 5, 'nama' => 'Kabupaten Sarolangun' ),
            array( 'provinsi_id' => 5, 'nama' => 'Kabupaten Batang Hari' ),
            array( 'provinsi_id' => 5, 'nama' => 'Kabupaten Muaro Jambi' ),
            array( 'provinsi_id' => 5, 'nama' => 'Kabupaten Tanjung Jabung Timur' ),
            array( 'provinsi_id' => 5, 'nama' => 'Kabupaten Tanjung Jabung Barat' ),
            array( 'provinsi_id' => 5, 'nama' => 'Kabupaten Tebo' ),
            array( 'provinsi_id' => 5, 'nama' => 'Kabupaten Bungo' ),
            array( 'provinsi_id' => 5, 'nama' => 'Kota Jambi' ),
            array( 'provinsi_id' => 5, 'nama' => 'Kota Sungai Penuh' ),

            // Provinsi Sumatera Selatan
            array( 'provinsi_id' => 6, 'nama' => 'Kabupaten Ogan Komering Ulu' ),
            array( 'provinsi_id' => 6, 'nama' => 'Kabupaten Ogan Komering Ilir' ),
            array( 'provinsi_id' => 6, 'nama' => 'Kabupaten Muara Enim' ),
            array( 'provinsi_id' => 6, 'nama' => 'Kabupaten Lahat' ),
            array( 'provinsi_id' => 6, 'nama' => 'Kabupaten Musi Rawas' ),
            array( 'provinsi_id' => 6, 'nama' => 'Kabupaten Musi Banyuasin' ),
            array( 'provinsi_id' => 6, 'nama' => 'Kabupaten Banyu Asin' ),
            array( 'provinsi_id' => 6, 'nama' => 'Kabupaten Ogan Komering Ulu Selatan' ),
            array( 'provinsi_id' => 6, 'nama' => 'Kabupaten Ogan Komering Ulu Timur' ),
            array( 'provinsi_id' => 6, 'nama' => 'Kabupaten Ogan Ilir' ),
            array( 'provinsi_id' => 6, 'nama' => 'Kabupaten Empat Lawang' ),
            array( 'provinsi_id' => 6, 'nama' => 'Kabupaten Penukal Abab Lematang Ilir' ),
            array( 'provinsi_id' => 6, 'nama' => 'Kabupaten Musi Rawas Utara' ),
            array( 'provinsi_id' => 6, 'nama' => 'Kota Palembang' ),
            array( 'provinsi_id' => 6, 'nama' => 'Kota Prabumulih' ),
            array( 'provinsi_id' => 6, 'nama' => 'Kota Pagar Alam' ),
            array( 'provinsi_id' => 6, 'nama' => 'Kota Lubuklinggau' ),

            // Provinsi Bengkulu
            array( 'provinsi_id' => 7, 'nama' => 'Kabupaten Bengkulu Selatan' ),
            array( 'provinsi_id' => 7, 'nama' => 'Kabupaten Rejang Lebong' ),
            array( 'provinsi_id' => 7, 'nama' => 'Kabupaten Bengkulu Utara' ),
            array( 'provinsi_id' => 7, 'nama' => 'Kabupaten Kaur' ),
            array( 'provinsi_id' => 7, 'nama' => 'Kabupaten Seluma' ),
            array( 'provinsi_id' => 7, 'nama' => 'Kabupaten Mukomuko' ),
            array( 'provinsi_id' => 7, 'nama' => 'Kabupaten Lebong' ),
            array( 'provinsi_id' => 7, 'nama' => 'Kabupaten Kepahiang' ),
            array( 'provinsi_id' => 7, 'nama' => 'Kabupaten Bengkulu Tengah' ),
            array( 'provinsi_id' => 7, 'nama' => 'Kota Bengkulu' ),

            // Provinsi Lampung
            array( 'provinsi_id' => 8, 'nama' => 'Kabupaten Lampung Barat' ),
            array( 'provinsi_id' => 8, 'nama' => 'Kabupaten Tanggamus' ),
            array( 'provinsi_id' => 8, 'nama' => 'Kabupaten Lampung Selatan' ),
            array( 'provinsi_id' => 8, 'nama' => 'Kabupaten Lampung Timur' ),
            array( 'provinsi_id' => 8, 'nama' => 'Kabupaten Lampung Tengah' ),
            array( 'provinsi_id' => 8, 'nama' => 'Kabupaten Lampung Utara' ),
            array( 'provinsi_id' => 8, 'nama' => 'Kabupaten Way Kanan' ),
            array( 'provinsi_id' => 8, 'nama' => 'Kabupaten Tulangbawang' ),
            array( 'provinsi_id' => 8, 'nama' => 'Kabupaten Pesawaran' ),
            array( 'provinsi_id' => 8, 'nama' => 'Kabupaten Pringsewu' ),
            array( 'provinsi_id' => 8, 'nama' => 'Kabupaten Mesuji' ),
            array( 'provinsi_id' => 8, 'nama' => 'Kabupaten Tulang Bawang Barat' ),
            array( 'provinsi_id' => 8, 'nama' => 'Kabupaten Pesisir Barat' ),
            array( 'provinsi_id' => 8, 'nama' => 'Kota Bandar Lampung' ),
            array( 'provinsi_id' => 8, 'nama' => 'Kota Metro' ),

            // Provinsi Kepulauan Bangka Belitung
            array( 'provinsi_id' => 9, 'nama' => 'Kabupaten Bangka' ),
            array( 'provinsi_id' => 9, 'nama' => 'Kabupaten Belitung' ),
            array( 'provinsi_id' => 9, 'nama' => 'Kabupaten Bangka Barat' ),
            array( 'provinsi_id' => 9, 'nama' => 'Kabupaten Bangka Tengah' ),
            array( 'provinsi_id' => 9, 'nama' => 'Kabupaten Bangka Selatan' ),
            array( 'provinsi_id' => 9, 'nama' => 'Kabupaten Belitung Timur' ),
            array( 'provinsi_id' => 9, 'nama' => 'Kota Pangkal Pinang' ),

            // Provinsi Kepulauan Riau
            array( 'provinsi_id' => 10, 'nama' => 'Kabupaten Karimun' ),
            array( 'provinsi_id' => 10, 'nama' => 'Kabupaten Bintan' ),
            array( 'provinsi_id' => 10, 'nama' => 'Kabupaten Natuna' ),
            array( 'provinsi_id' => 10, 'nama' => 'Kabupaten Lingga' ),
            array( 'provinsi_id' => 10, 'nama' => 'Kabupaten Kepulauan Anambas' ),
            array( 'provinsi_id' => 10, 'nama' => 'Kota B A T A M' ),
            array( 'provinsi_id' => 10, 'nama' => 'Kota Tanjung Pinang' ),

            // Provinsi Dki Jakarta
            array( 'provinsi_id' => 11, 'nama' => 'Kabupaten Kepulauan Seribu' ),
            array( 'provinsi_id' => 11, 'nama' => 'Kota Jakarta Selatan' ),
            array( 'provinsi_id' => 11, 'nama' => 'Kota Jakarta Timur' ),
            array( 'provinsi_id' => 11, 'nama' => 'Kota Jakarta Pusat' ),
            array( 'provinsi_id' => 11, 'nama' => 'Kota Jakarta Barat' ),
            array( 'provinsi_id' => 11, 'nama' => 'Kota Jakarta Utara' ),

            // Provinsi Jawa Barat
            array( 'provinsi_id' => 12, 'nama' => 'Kabupaten Bogor' ),
            array( 'provinsi_id' => 12, 'nama' => 'Kabupaten Sukabumi' ),
            array( 'provinsi_id' => 12, 'nama' => 'Kabupaten Cianjur' ),
            array( 'provinsi_id' => 12, 'nama' => 'Kabupaten Bandung' ),
            array( 'provinsi_id' => 12, 'nama' => 'Kabupaten Garut' ),
            array( 'provinsi_id' => 12, 'nama' => 'Kabupaten Tasikmalaya' ),
            array( 'provinsi_id' => 12, 'nama' => 'Kabupaten Ciamis' ),
            array( 'provinsi_id' => 12, 'nama' => 'Kabupaten Kuningan' ),
            array( 'provinsi_id' => 12, 'nama' => 'Kabupaten Cirebon' ),
            array( 'provinsi_id' => 12, 'nama' => 'Kabupaten Majalengka' ),
            array( 'provinsi_id' => 12, 'nama' => 'Kabupaten Sumedang' ),
            array( 'provinsi_id' => 12, 'nama' => 'Kabupaten Indramayu' ),
            array( 'provinsi_id' => 12, 'nama' => 'Kabupaten Subang' ),
            array( 'provinsi_id' => 12, 'nama' => 'Kabupaten Purwakarta' ),
            array( 'provinsi_id' => 12, 'nama' => 'Kabupaten Karawang' ),
            array( 'provinsi_id' => 12, 'nama' => 'Kabupaten Bekasi' ),
            array( 'provinsi_id' => 12, 'nama' => 'Kabupaten Bandung Barat' ),
            array( 'provinsi_id' => 12, 'nama' => 'Kabupaten Pangandaran' ),
            array( 'provinsi_id' => 12, 'nama' => 'Kota Bogor' ),
            array( 'provinsi_id' => 12, 'nama' => 'Kota Sukabumi' ),
            array( 'provinsi_id' => 12, 'nama' => 'Kota Bandung' ),
            array( 'provinsi_id' => 12, 'nama' => 'Kota Cirebon' ),
            array( 'provinsi_id' => 12, 'nama' => 'Kota Bekasi' ),
            array( 'provinsi_id' => 12, 'nama' => 'Kota Depok' ),
            array( 'provinsi_id' => 12, 'nama' => 'Kota Cimahi' ),
            array( 'provinsi_id' => 12, 'nama' => 'Kota Tasikmalaya' ),
            array( 'provinsi_id' => 12, 'nama' => 'Kota Banjar' ),

            // Provinsi Jawa Tengah
            array( 'provinsi_id' => 13, 'nama' => 'Kabupaten Cilacap' ),
            array( 'provinsi_id' => 13, 'nama' => 'Kabupaten Banyumas' ),
            array( 'provinsi_id' => 13, 'nama' => 'Kabupaten Purbalingga' ),
            array( 'provinsi_id' => 13, 'nama' => 'Kabupaten Banjarnegara' ),
            array( 'provinsi_id' => 13, 'nama' => 'Kabupaten Kebumen' ),
            array( 'provinsi_id' => 13, 'nama' => 'Kabupaten Purworejo' ),
            array( 'provinsi_id' => 13, 'nama' => 'Kabupaten Wonosobo' ),
            array( 'provinsi_id' => 13, 'nama' => 'Kabupaten Magelang' ),
            array( 'provinsi_id' => 13, 'nama' => 'Kabupaten Boyolali' ),
            array( 'provinsi_id' => 13, 'nama' => 'Kabupaten Klaten' ),
            array( 'provinsi_id' => 13, 'nama' => 'Kabupaten Sukoharjo' ),
            array( 'provinsi_id' => 13, 'nama' => 'Kabupaten Wonogiri' ),
            array( 'provinsi_id' => 13, 'nama' => 'Kabupaten Karanganyar' ),
            array( 'provinsi_id' => 13, 'nama' => 'Kabupaten Sragen' ),
            array( 'provinsi_id' => 13, 'nama' => 'Kabupaten Grobogan' ),
            array( 'provinsi_id' => 13, 'nama' => 'Kabupaten Blora' ),
            array( 'provinsi_id' => 13, 'nama' => 'Kabupaten Rembang' ),
            array( 'provinsi_id' => 13, 'nama' => 'Kabupaten Pati' ),
            array( 'provinsi_id' => 13, 'nama' => 'Kabupaten Kudus' ),
            array( 'provinsi_id' => 13, 'nama' => 'Kabupaten Jepara' ),
            array( 'provinsi_id' => 13, 'nama' => 'Kabupaten Demak' ),
            array( 'provinsi_id' => 13, 'nama' => 'Kabupaten Semarang' ),
            array( 'provinsi_id' => 13, 'nama' => 'Kabupaten Temanggung' ),
            array( 'provinsi_id' => 13, 'nama' => 'Kabupaten Kendal' ),
            array( 'provinsi_id' => 13, 'nama' => 'Kabupaten Batang' ),
            array( 'provinsi_id' => 13, 'nama' => 'Kabupaten Pekalongan' ),
            array( 'provinsi_id' => 13, 'nama' => 'Kabupaten Pemalang' ),
            array( 'provinsi_id' => 13, 'nama' => 'Kabupaten Tegal' ),
            array( 'provinsi_id' => 13, 'nama' => 'Kabupaten Brebes' ),
            array( 'provinsi_id' => 13, 'nama' => 'Kota Magelang' ),
            array( 'provinsi_id' => 13, 'nama' => 'Kota Surakarta' ),
            array( 'provinsi_id' => 13, 'nama' => 'Kota Salatiga' ),
            array( 'provinsi_id' => 13, 'nama' => 'Kota Semarang' ),
            array( 'provinsi_id' => 13, 'nama' => 'Kota Pekalongan' ),
            array( 'provinsi_id' => 13, 'nama' => 'Kota Tegal' ),

            // Provinsi Di Yogyakarta
            array( 'provinsi_id' => 14, 'nama' => 'Kabupaten Kulon Progo' ),
            array( 'provinsi_id' => 14, 'nama' => 'Kabupaten Bantul' ),
            array( 'provinsi_id' => 14, 'nama' => 'Kabupaten Gunung Kidul' ),
            array( 'provinsi_id' => 14, 'nama' => 'Kabupaten Sleman' ),
            array( 'provinsi_id' => 14, 'nama' => 'Kota Yogyakarta' ),

            // Provinsi Jawa Timur
            array( 'provinsi_id' => 15, 'nama' => 'Kabupaten Pacitan' ),
            array( 'provinsi_id' => 15, 'nama' => 'Kabupaten Ponorogo' ),
            array( 'provinsi_id' => 15, 'nama' => 'Kabupaten Trenggalek' ),
            array( 'provinsi_id' => 15, 'nama' => 'Kabupaten Tulungagung' ),
            array( 'provinsi_id' => 15, 'nama' => 'Kabupaten Blitar' ),
            array( 'provinsi_id' => 15, 'nama' => 'Kabupaten Kediri' ),
            array( 'provinsi_id' => 15, 'nama' => 'Kabupaten Malang' ),
            array( 'provinsi_id' => 15, 'nama' => 'Kabupaten Lumajang' ),
            array( 'provinsi_id' => 15, 'nama' => 'Kabupaten Jember' ),
            array( 'provinsi_id' => 15, 'nama' => 'Kabupaten Banyuwangi' ),
            array( 'provinsi_id' => 15, 'nama' => 'Kabupaten Bondowoso' ),
            array( 'provinsi_id' => 15, 'nama' => 'Kabupaten Situbondo' ),
            array( 'provinsi_id' => 15, 'nama' => 'Kabupaten Probolinggo' ),
            array( 'provinsi_id' => 15, 'nama' => 'Kabupaten Pasuruan' ),
            array( 'provinsi_id' => 15, 'nama' => 'Kabupaten Sidoarjo' ),
            array( 'provinsi_id' => 15, 'nama' => 'Kabupaten Mojokerto' ),
            array( 'provinsi_id' => 15, 'nama' => 'Kabupaten Jombang' ),
            array( 'provinsi_id' => 15, 'nama' => 'Kabupaten Nganjuk' ),
            array( 'provinsi_id' => 15, 'nama' => 'Kabupaten Madiun' ),
            array( 'provinsi_id' => 15, 'nama' => 'Kabupaten Magetan' ),
            array( 'provinsi_id' => 15, 'nama' => 'Kabupaten Ngawi' ),
            array( 'provinsi_id' => 15, 'nama' => 'Kabupaten Bojonegoro' ),
            array( 'provinsi_id' => 15, 'nama' => 'Kabupaten Tuban' ),
            array( 'provinsi_id' => 15, 'nama' => 'Kabupaten Lamongan' ),
            array( 'provinsi_id' => 15, 'nama' => 'Kabupaten Gresik' ),
            array( 'provinsi_id' => 15, 'nama' => 'Kabupaten Bangkalan' ),
            array( 'provinsi_id' => 15, 'nama' => 'Kabupaten Sampang' ),
            array( 'provinsi_id' => 15, 'nama' => 'Kabupaten Pamekasan' ),
            array( 'provinsi_id' => 15, 'nama' => 'Kabupaten Sumenep' ),
            array( 'provinsi_id' => 15, 'nama' => 'Kota Kediri' ),
            array( 'provinsi_id' => 15, 'nama' => 'Kota Blitar' ),
            array( 'provinsi_id' => 15, 'nama' => 'Kota Malang' ),
            array( 'provinsi_id' => 15, 'nama' => 'Kota Probolinggo' ),
            array( 'provinsi_id' => 15, 'nama' => 'Kota Pasuruan' ),
            array( 'provinsi_id' => 15, 'nama' => 'Kota Mojokerto' ),
            array( 'provinsi_id' => 15, 'nama' => 'Kota Madiun' ),
            array( 'provinsi_id' => 15, 'nama' => 'Kota Surabaya' ),
            array( 'provinsi_id' => 15, 'nama' => 'Kota Batu' ),

            // Provinsi Banten
            array( 'provinsi_id' => 16, 'nama' => 'Kabupaten Pandeglang' ),
            array( 'provinsi_id' => 16, 'nama' => 'Kabupaten Lebak' ),
            array( 'provinsi_id' => 16, 'nama' => 'Kabupaten Tangerang' ),
            array( 'provinsi_id' => 16, 'nama' => 'Kabupaten Serang' ),
            array( 'provinsi_id' => 16, 'nama' => 'Kota Tangerang' ),
            array( 'provinsi_id' => 16, 'nama' => 'Kota Cilegon' ),
            array( 'provinsi_id' => 16, 'nama' => 'Kota Serang' ),
            array( 'provinsi_id' => 16, 'nama' => 'Kota Tangerang Selatan' ),

            // Provinsi Bali
            array( 'provinsi_id' => 17, 'nama' => 'Kabupaten Jembrana' ),
            array( 'provinsi_id' => 17, 'nama' => 'Kabupaten Tabanan' ),
            array( 'provinsi_id' => 17, 'nama' => 'Kabupaten Badung' ),
            array( 'provinsi_id' => 17, 'nama' => 'Kabupaten Gianyar' ),
            array( 'provinsi_id' => 17, 'nama' => 'Kabupaten Klungkung' ),
            array( 'provinsi_id' => 17, 'nama' => 'Kabupaten Bangli' ),
            array( 'provinsi_id' => 17, 'nama' => 'Kabupaten Karang Asem' ),
            array( 'provinsi_id' => 17, 'nama' => 'Kabupaten Buleleng' ),
            array( 'provinsi_id' => 17, 'nama' => 'Kota Denpasar' ),

            // Provinsi Nusa Tenggara Barat
            array( 'provinsi_id' => 18, 'nama' => 'Kabupaten Lombok Barat' ),
            array( 'provinsi_id' => 18, 'nama' => 'Kabupaten Lombok Tengah' ),
            array( 'provinsi_id' => 18, 'nama' => 'Kabupaten Lombok Timur' ),
            array( 'provinsi_id' => 18, 'nama' => 'Kabupaten Sumbawa' ),
            array( 'provinsi_id' => 18, 'nama' => 'Kabupaten Dompu' ),
            array( 'provinsi_id' => 18, 'nama' => 'Kabupaten Bima' ),
            array( 'provinsi_id' => 18, 'nama' => 'Kabupaten Sumbawa Barat' ),
            array( 'provinsi_id' => 18, 'nama' => 'Kabupaten Lombok Utara' ),
            array( 'provinsi_id' => 18, 'nama' => 'Kota Mataram' ),
            array( 'provinsi_id' => 18, 'nama' => 'Kota Bima' ),

            // Provinsi Nusa Tenggara Timur
            array( 'provinsi_id' => 19, 'nama' => 'Kabupaten Sumba Barat' ),
            array( 'provinsi_id' => 19, 'nama' => 'Kabupaten Sumba Timur' ),
            array( 'provinsi_id' => 19, 'nama' => 'Kabupaten Kupang' ),
            array( 'provinsi_id' => 19, 'nama' => 'Kabupaten Timor Tengah Selatan' ),
            array( 'provinsi_id' => 19, 'nama' => 'Kabupaten Timor Tengah Utara' ),
            array( 'provinsi_id' => 19, 'nama' => 'Kabupaten Belu' ),
            array( 'provinsi_id' => 19, 'nama' => 'Kabupaten Alor' ),
            array( 'provinsi_id' => 19, 'nama' => 'Kabupaten Lembata' ),
            array( 'provinsi_id' => 19, 'nama' => 'Kabupaten Flores Timur' ),
            array( 'provinsi_id' => 19, 'nama' => 'Kabupaten Sikka' ),
            array( 'provinsi_id' => 19, 'nama' => 'Kabupaten Ende' ),
            array( 'provinsi_id' => 19, 'nama' => 'Kabupaten Ngada' ),
            array( 'provinsi_id' => 19, 'nama' => 'Kabupaten Manggarai' ),
            array( 'provinsi_id' => 19, 'nama' => 'Kabupaten Rote Ndao' ),
            array( 'provinsi_id' => 19, 'nama' => 'Kabupaten Manggarai Barat' ),
            array( 'provinsi_id' => 19, 'nama' => 'Kabupaten Sumba Tengah' ),
            array( 'provinsi_id' => 19, 'nama' => 'Kabupaten Sumba Barat Daya' ),
            array( 'provinsi_id' => 19, 'nama' => 'Kabupaten Nagekeo' ),
            array( 'provinsi_id' => 19, 'nama' => 'Kabupaten Manggarai Timur' ),
            array( 'provinsi_id' => 19, 'nama' => 'Kabupaten Sabu Raijua' ),
            array( 'provinsi_id' => 19, 'nama' => 'Kabupaten Malaka' ),
            array( 'provinsi_id' => 19, 'nama' => 'Kota Kupang' ),

            // Provinsi Kalimantan Barat
            array( 'provinsi_id' => 20, 'nama' => 'Kabupaten Sambas' ),
            array( 'provinsi_id' => 20, 'nama' => 'Kabupaten Bengkayang' ),
            array( 'provinsi_id' => 20, 'nama' => 'Kabupaten Landak' ),
            array( 'provinsi_id' => 20, 'nama' => 'Kabupaten Mempawah' ),
            array( 'provinsi_id' => 20, 'nama' => 'Kabupaten Sanggau' ),
            array( 'provinsi_id' => 20, 'nama' => 'Kabupaten Ketapang' ),
            array( 'provinsi_id' => 20, 'nama' => 'Kabupaten Sintang' ),
            array( 'provinsi_id' => 20, 'nama' => 'Kabupaten Kapuas Hulu' ),
            array( 'provinsi_id' => 20, 'nama' => 'Kabupaten Sekadau' ),
            array( 'provinsi_id' => 20, 'nama' => 'Kabupaten Melawi' ),
            array( 'provinsi_id' => 20, 'nama' => 'Kabupaten Kayong Utara' ),
            array( 'provinsi_id' => 20, 'nama' => 'Kabupaten Kubu Raya' ),
            array( 'provinsi_id' => 20, 'nama' => 'Kota Pontianak' ),
            array( 'provinsi_id' => 20, 'nama' => 'Kota Singkawang' ),

            // Provinsi Kalimantan Tengah
            array( 'provinsi_id' => 21, 'nama' => 'Kabupaten Kotawaringin Barat' ),
            array( 'provinsi_id' => 21, 'nama' => 'Kabupaten Kotawaringin Timur' ),
            array( 'provinsi_id' => 21, 'nama' => 'Kabupaten Kapuas' ),
            array( 'provinsi_id' => 21, 'nama' => 'Kabupaten Barito Selatan' ),
            array( 'provinsi_id' => 21, 'nama' => 'Kabupaten Barito Utara' ),
            array( 'provinsi_id' => 21, 'nama' => 'Kabupaten Sukamara' ),
            array( 'provinsi_id' => 21, 'nama' => 'Kabupaten Lamandau' ),
            array( 'provinsi_id' => 21, 'nama' => 'Kabupaten Seruyan' ),
            array( 'provinsi_id' => 21, 'nama' => 'Kabupaten Katingan' ),
            array( 'provinsi_id' => 21, 'nama' => 'Kabupaten Pulang Pisau' ),
            array( 'provinsi_id' => 21, 'nama' => 'Kabupaten Gunung Mas' ),
            array( 'provinsi_id' => 21, 'nama' => 'Kabupaten Barito Timur' ),
            array( 'provinsi_id' => 21, 'nama' => 'Kabupaten Murung Raya' ),
            array( 'provinsi_id' => 21, 'nama' => 'Kota Palangka Raya' ),

            // Provinsi Kalimantan Selatan
            array( 'provinsi_id' => 22, 'nama' => 'Kabupaten Tanah Laut' ),
            array( 'provinsi_id' => 22, 'nama' => 'Kabupaten Kota Baru' ),
            array( 'provinsi_id' => 22, 'nama' => 'Kabupaten Banjar' ),
            array( 'provinsi_id' => 22, 'nama' => 'Kabupaten Barito Kuala' ),
            array( 'provinsi_id' => 22, 'nama' => 'Kabupaten Tapin' ),
            array( 'provinsi_id' => 22, 'nama' => 'Kabupaten Hulu Sungai Selatan' ),
            array( 'provinsi_id' => 22, 'nama' => 'Kabupaten Hulu Sungai Tengah' ),
            array( 'provinsi_id' => 22, 'nama' => 'Kabupaten Hulu Sungai Utara' ),
            array( 'provinsi_id' => 22, 'nama' => 'Kabupaten Tabalong' ),
            array( 'provinsi_id' => 22, 'nama' => 'Kabupaten Tanah Bumbu' ),
            array( 'provinsi_id' => 22, 'nama' => 'Kabupaten Balangan' ),
            array( 'provinsi_id' => 22, 'nama' => 'Kota Banjarmasin' ),
            array( 'provinsi_id' => 22, 'nama' => 'Kota Banjar Baru' ),

            // Provinsi Kalimantan Timur
            array( 'provinsi_id' => 23, 'nama' => 'Kabupaten Paser' ),
            array( 'provinsi_id' => 23, 'nama' => 'Kabupaten Kutai Barat' ),
            array( 'provinsi_id' => 23, 'nama' => 'Kabupaten Kutai Kartanegara' ),
            array( 'provinsi_id' => 23, 'nama' => 'Kabupaten Kutai Timur' ),
            array( 'provinsi_id' => 23, 'nama' => 'Kabupaten Berau' ),
            array( 'provinsi_id' => 23, 'nama' => 'Kabupaten Penajam Paser Utara' ),
            array( 'provinsi_id' => 23, 'nama' => 'Kabupaten Mahakam Hulu' ),
            array( 'provinsi_id' => 23, 'nama' => 'Kota Balikpapan' ),
            array( 'provinsi_id' => 23, 'nama' => 'Kota Samarinda' ),
            array( 'provinsi_id' => 23, 'nama' => 'Kota Bontang' ),

            // Provinsi Kalimantan Utara
            array( 'provinsi_id' => 24, 'nama' => 'Kabupaten Malinau' ),
            array( 'provinsi_id' => 24, 'nama' => 'Kabupaten Bulungan' ),
            array( 'provinsi_id' => 24, 'nama' => 'Kabupaten Tana Tidung' ),
            array( 'provinsi_id' => 24, 'nama' => 'Kabupaten Nunukan' ),
            array( 'provinsi_id' => 24, 'nama' => 'Kota Tarakan' ),

            // Provinsi Sulawesi Utara
            array( 'provinsi_id' => 25, 'nama' => 'Kabupaten Bolaang Mongondow' ),
            array( 'provinsi_id' => 25, 'nama' => 'Kabupaten Minahasa' ),
            array( 'provinsi_id' => 25, 'nama' => 'Kabupaten Kepulauan Sangihe' ),
            array( 'provinsi_id' => 25, 'nama' => 'Kabupaten Kepulauan Talaud' ),
            array( 'provinsi_id' => 25, 'nama' => 'Kabupaten Minahasa Selatan' ),
            array( 'provinsi_id' => 25, 'nama' => 'Kabupaten Minahasa Utara' ),
            array( 'provinsi_id' => 25, 'nama' => 'Kabupaten Bolaang Mongondow Utara' ),
            array( 'provinsi_id' => 25, 'nama' => 'Kabupaten Siau Tagulandang Biaro' ),
            array( 'provinsi_id' => 25, 'nama' => 'Kabupaten Minahasa Tenggara' ),
            array( 'provinsi_id' => 25, 'nama' => 'Kabupaten Bolaang Mongondow Selatan' ),
            array( 'provinsi_id' => 25, 'nama' => 'Kabupaten Bolaang Mongondow Timur' ),
            array( 'provinsi_id' => 25, 'nama' => 'Kota Manado' ),
            array( 'provinsi_id' => 25, 'nama' => 'Kota Bitung' ),
            array( 'provinsi_id' => 25, 'nama' => 'Kota Tomohon' ),
            array( 'provinsi_id' => 25, 'nama' => 'Kota Kotamobagu' ),

            // Provinsi Sulawesi Tengah
            array( 'provinsi_id' => 26, 'nama' => 'Kabupaten Banggai Kepulauan' ),
            array( 'provinsi_id' => 26, 'nama' => 'Kabupaten Banggai' ),
            array( 'provinsi_id' => 26, 'nama' => 'Kabupaten Morowali' ),
            array( 'provinsi_id' => 26, 'nama' => 'Kabupaten Poso' ),
            array( 'provinsi_id' => 26, 'nama' => 'Kabupaten Donggala' ),
            array( 'provinsi_id' => 26, 'nama' => 'Kabupaten Toli-toli' ),
            array( 'provinsi_id' => 26, 'nama' => 'Kabupaten Buol' ),
            array( 'provinsi_id' => 26, 'nama' => 'Kabupaten Parigi Moutong' ),
            array( 'provinsi_id' => 26, 'nama' => 'Kabupaten Tojo Una-una' ),
            array( 'provinsi_id' => 26, 'nama' => 'Kabupaten Sigi' ),
            array( 'provinsi_id' => 26, 'nama' => 'Kabupaten Banggai Laut' ),
            array( 'provinsi_id' => 26, 'nama' => 'Kabupaten Morowali Utara' ),
            array( 'provinsi_id' => 26, 'nama' => 'Kota Palu' ),

            // Provinsi Sulawesi Selatan
            array( 'provinsi_id' => 27, 'nama' => 'Kabupaten Kepulauan Selayar' ),
            array( 'provinsi_id' => 27, 'nama' => 'Kabupaten Bulukumba' ),
            array( 'provinsi_id' => 27, 'nama' => 'Kabupaten Bantaeng' ),
            array( 'provinsi_id' => 27, 'nama' => 'Kabupaten Jeneponto' ),
            array( 'provinsi_id' => 27, 'nama' => 'Kabupaten Takalar' ),
            array( 'provinsi_id' => 27, 'nama' => 'Kabupaten Gowa' ),
            array( 'provinsi_id' => 27, 'nama' => 'Kabupaten Sinjai' ),
            array( 'provinsi_id' => 27, 'nama' => 'Kabupaten Maros' ),
            array( 'provinsi_id' => 27, 'nama' => 'Kabupaten Pangkajene Dan Kepulauan' ),
            array( 'provinsi_id' => 27, 'nama' => 'Kabupaten Barru' ),
            array( 'provinsi_id' => 27, 'nama' => 'Kabupaten Bone' ),
            array( 'provinsi_id' => 27, 'nama' => 'Kabupaten Soppeng' ),
            array( 'provinsi_id' => 27, 'nama' => 'Kabupaten Wajo' ),
            array( 'provinsi_id' => 27, 'nama' => 'Kabupaten Sidenreng Rappang' ),
            array( 'provinsi_id' => 27, 'nama' => 'Kabupaten Pinrang' ),
            array( 'provinsi_id' => 27, 'nama' => 'Kabupaten Enrekang' ),
            array( 'provinsi_id' => 27, 'nama' => 'Kabupaten Luwu' ),
            array( 'provinsi_id' => 27, 'nama' => 'Kabupaten Tana Toraja' ),
            array( 'provinsi_id' => 27, 'nama' => 'Kabupaten Luwu Utara' ),
            array( 'provinsi_id' => 27, 'nama' => 'Kabupaten Luwu Timur' ),
            array( 'provinsi_id' => 27, 'nama' => 'Kabupaten Toraja Utara' ),
            array( 'provinsi_id' => 27, 'nama' => 'Kota Makassar' ),
            array( 'provinsi_id' => 27, 'nama' => 'Kota Parepare' ),
            array( 'provinsi_id' => 27, 'nama' => 'Kota Palopo' ),

            // Provinsi Sulawesi Tenggara
            array( 'provinsi_id' => 28, 'nama' => 'Kabupaten Buton' ),
            array( 'provinsi_id' => 28, 'nama' => 'Kabupaten Muna' ),
            array( 'provinsi_id' => 28, 'nama' => 'Kabupaten Konawe' ),
            array( 'provinsi_id' => 28, 'nama' => 'Kabupaten Kolaka' ),
            array( 'provinsi_id' => 28, 'nama' => 'Kabupaten Konawe Selatan' ),
            array( 'provinsi_id' => 28, 'nama' => 'Kabupaten Bombana' ),
            array( 'provinsi_id' => 28, 'nama' => 'Kabupaten Wakatobi' ),
            array( 'provinsi_id' => 28, 'nama' => 'Kabupaten Kolaka Utara' ),
            array( 'provinsi_id' => 28, 'nama' => 'Kabupaten Buton Utara' ),
            array( 'provinsi_id' => 28, 'nama' => 'Kabupaten Konawe Utara' ),
            array( 'provinsi_id' => 28, 'nama' => 'Kabupaten Kolaka Timur' ),
            array( 'provinsi_id' => 28, 'nama' => 'Kabupaten Konawe Kepulauan' ),
            array( 'provinsi_id' => 28, 'nama' => 'Kabupaten Muna Barat' ),
            array( 'provinsi_id' => 28, 'nama' => 'Kabupaten Buton Tengah' ),
            array( 'provinsi_id' => 28, 'nama' => 'Kabupaten Buton Selatan' ),
            array( 'provinsi_id' => 28, 'nama' => 'Kota Kendari' ),
            array( 'provinsi_id' => 28, 'nama' => 'Kota Baubau' ),

            // Provinsi Gorontalo
            array( 'provinsi_id' => 29, 'nama' => 'Kabupaten Boalemo' ),
            array( 'provinsi_id' => 29, 'nama' => 'Kabupaten Gorontalo' ),
            array( 'provinsi_id' => 29, 'nama' => 'Kabupaten Pohuwato' ),
            array( 'provinsi_id' => 29, 'nama' => 'Kabupaten Bone Bolango' ),
            array( 'provinsi_id' => 29, 'nama' => 'Kabupaten Gorontalo Utara' ),
            array( 'provinsi_id' => 29, 'nama' => 'Kota Gorontalo' ),

            // Provinsi Sulawesi Barat
            array( 'provinsi_id' => 30, 'nama' => 'Kabupaten Majene' ),
            array( 'provinsi_id' => 30, 'nama' => 'Kabupaten Polewali Mandar' ),
            array( 'provinsi_id' => 30, 'nama' => 'Kabupaten Mamasa' ),
            array( 'provinsi_id' => 30, 'nama' => 'Kabupaten Mamuju' ),
            array( 'provinsi_id' => 30, 'nama' => 'Kabupaten Mamuju Utara' ),
            array( 'provinsi_id' => 30, 'nama' => 'Kabupaten Mamuju Tengah' ),

            // Provinsi Maluku
            array( 'provinsi_id' => 31, 'nama' => 'Kabupaten Maluku Tenggara Barat' ),
            array( 'provinsi_id' => 31, 'nama' => 'Kabupaten Maluku Tenggara' ),
            array( 'provinsi_id' => 31, 'nama' => 'Kabupaten Maluku Tengah' ),
            array( 'provinsi_id' => 31, 'nama' => 'Kabupaten Buru' ),
            array( 'provinsi_id' => 31, 'nama' => 'Kabupaten Kepulauan Aru' ),
            array( 'provinsi_id' => 31, 'nama' => 'Kabupaten Seram Bagian Barat' ),
            array( 'provinsi_id' => 31, 'nama' => 'Kabupaten Seram Bagian Timur' ),
            array( 'provinsi_id' => 31, 'nama' => 'Kabupaten Maluku Barat Daya' ),
            array( 'provinsi_id' => 31, 'nama' => 'Kabupaten Buru Selatan' ),
            array( 'provinsi_id' => 31, 'nama' => 'Kota Ambon' ),
            array( 'provinsi_id' => 31, 'nama' => 'Kota Tual' ),

            // Provinsi Maluku Utara
            array( 'provinsi_id' => 32, 'nama' => 'Kabupaten Halmahera Barat' ),
            array( 'provinsi_id' => 32, 'nama' => 'Kabupaten Halmahera Tengah' ),
            array( 'provinsi_id' => 32, 'nama' => 'Kabupaten Kepulauan Sula' ),
            array( 'provinsi_id' => 32, 'nama' => 'Kabupaten Halmahera Selatan' ),
            array( 'provinsi_id' => 32, 'nama' => 'Kabupaten Halmahera Utara' ),
            array( 'provinsi_id' => 32, 'nama' => 'Kabupaten Halmahera Timur' ),
            array( 'provinsi_id' => 32, 'nama' => 'Kabupaten Pulau Morotai' ),
            array( 'provinsi_id' => 32, 'nama' => 'Kabupaten Pulau Taliabu' ),
            array( 'provinsi_id' => 32, 'nama' => 'Kota Ternate' ),
            array( 'provinsi_id' => 32, 'nama' => 'Kota Tidore Kepulauan' ),

            // Provinsi Papua Barat
            array( 'provinsi_id' => 33, 'nama' => 'Kabupaten Fakfak' ),
            array( 'provinsi_id' => 33, 'nama' => 'Kabupaten Kaimana' ),
            array( 'provinsi_id' => 33, 'nama' => 'Kabupaten Teluk Wondama' ),
            array( 'provinsi_id' => 33, 'nama' => 'Kabupaten Teluk Bintuni' ),
            array( 'provinsi_id' => 33, 'nama' => 'Kabupaten Manokwari' ),
            array( 'provinsi_id' => 33, 'nama' => 'Kabupaten Sorong Selatan' ),
            array( 'provinsi_id' => 33, 'nama' => 'Kabupaten Sorong' ),
            array( 'provinsi_id' => 33, 'nama' => 'Kabupaten Raja Ampat' ),
            array( 'provinsi_id' => 33, 'nama' => 'Kabupaten Tambrauw' ),
            array( 'provinsi_id' => 33, 'nama' => 'Kabupaten Maybrat' ),
            array( 'provinsi_id' => 33, 'nama' => 'Kabupaten Manokwari Selatan' ),
            array( 'provinsi_id' => 33, 'nama' => 'Kabupaten Pegunungan Arfak' ),
            array( 'provinsi_id' => 33, 'nama' => 'Kota Sorong' ),

            // Provinsi Papua
            array( 'provinsi_id' => 34, 'nama' => 'Kabupaten Merauke' ),
            array( 'provinsi_id' => 34, 'nama' => 'Kabupaten Jayawijaya' ),
            array( 'provinsi_id' => 34, 'nama' => 'Kabupaten Jayapura' ),
            array( 'provinsi_id' => 34, 'nama' => 'Kabupaten Nabire' ),
            array( 'provinsi_id' => 34, 'nama' => 'Kabupaten Kepulauan Yapen' ),
            array( 'provinsi_id' => 34, 'nama' => 'Kabupaten Biak Numfor' ),
            array( 'provinsi_id' => 34, 'nama' => 'Kabupaten Paniai' ),
            array( 'provinsi_id' => 34, 'nama' => 'Kabupaten Puncak Jaya' ),
            array( 'provinsi_id' => 34, 'nama' => 'Kabupaten Mimika' ),
            array( 'provinsi_id' => 34, 'nama' => 'Kabupaten Boven Digoel' ),
            array( 'provinsi_id' => 34, 'nama' => 'Kabupaten Mappi' ),
            array( 'provinsi_id' => 34, 'nama' => 'Kabupaten Asmat' ),
            array( 'provinsi_id' => 34, 'nama' => 'Kabupaten Yahukimo' ),
            array( 'provinsi_id' => 34, 'nama' => 'Kabupaten Pegunungan Bintang' ),
            array( 'provinsi_id' => 34, 'nama' => 'Kabupaten Tolikara' ),
            array( 'provinsi_id' => 34, 'nama' => 'Kabupaten Sarmi' ),
            array( 'provinsi_id' => 34, 'nama' => 'Kabupaten Keerom' ),
            array( 'provinsi_id' => 34, 'nama' => 'Kabupaten Waropen' ),
            array( 'provinsi_id' => 34, 'nama' => 'Kabupaten Supiori' ),
            array( 'provinsi_id' => 34, 'nama' => 'Kabupaten Mamberamo Raya' ),
            array( 'provinsi_id' => 34, 'nama' => 'Kabupaten Nduga' ),
            array( 'provinsi_id' => 34, 'nama' => 'Kabupaten Lanny Jaya' ),
            array( 'provinsi_id' => 34, 'nama' => 'Kabupaten Mamberamo Tengah' ),
            array( 'provinsi_id' => 34, 'nama' => 'Kabupaten Yalimo' ),
            array( 'provinsi_id' => 34, 'nama' => 'Kabupaten Puncak' ),
            array( 'provinsi_id' => 34, 'nama' => 'Kabupaten Dogiyai' ),
            array( 'provinsi_id' => 34, 'nama' => 'Kabupaten Intan Jaya' ),
            array( 'provinsi_id' => 34, 'nama' => 'Kabupaten Deiyai' ),
            array( 'provinsi_id' => 34, 'nama' => 'Kota Jayapura' ),
        );

        foreach ($kabupaten as $item) {
            DB::table('kabupaten')->insert([
                'provinsi_id' => $item['provinsi_id'],
                'nama'        => $item['nama'],
            ]);
        }
    }
}
